AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template ECR Repo Cross-Account

Parameters:
  RepositoryName: 
    Type: String
    Default: go-oauth
  Env:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - hml
      - prd
  BusinessUnitName:
    Type: String
    Default: global
  PlatformName:
    Type: String
    Default: dockone
  ApplicationName:
    Type: String
    Default: go-oauth
  ComponentName:
    Type: String
    Default: go-oauth
  PciClassificationName:
    Type: String
    Default: non-pci
    AllowedValues:
      - pci
      - pci-connected
      - non-pci
  Owner:
    Type: String
    Default: architecture

Resources:
  EcrRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName
      ImageScanningConfiguration:
        ScanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep only the last 5 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 5
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Sid: CrossAccountPermission
            Effect: Allow
            Action:
              - ecr:BatchCheckLayerAvailability
              - ecr:BatchGetImage
              - ecr:CompleteLayerUpload
              - ecr:DescribeImages
              - ecr:DescribeRepositories
              - ecr:GetDownloadUrlForLayer
              - ecr:GetRepositoryPolicy
              - ecr:InitiateLayerUpload
              - ecr:ListImages
              - ecr:PutImage   
              - ecr:UploadLayerPart
            Principal:
              AWS:
                - arn:aws:iam::992382474575:root
      Tags:
        - Key: env
          Value: !Ref Env
        - Key: stack
          Value: !Sub ${AWS::StackName}
        - Key: name
          Value: !Ref RepositoryName
        - Key: resource
          Value: ecr
        - Key: business_unit
          Value: !Ref BusinessUnitName
        - Key: application
          Value: !Ref ApplicationName
        - Key: component
          Value: !Ref ComponentName
        - Key: owner
          Value: !Ref Owner
        - Key: pci_classification
          Value: !Ref PciClassificationName

Outputs:
  EcrRepo:
    Value: !GetAtt EcrRepo.RepositoryUri