name: Deploy Workload in EKS

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      AWS_ACCOUNT_ID:
        description: 'AWS account id'
        required: true
        default: '992382474575'
      REGION:
        description: 'AWS Region'
        required: true
        default: 'us-east-2'

env:
  GO_VERSION: 1.23.3

defaults:
  run:
    shell: bash
    
jobs:
  setup-environment:
    uses: ./.github/workflows/setup-environment.yaml
    with:
      AWS_ACCOUNT_ID: ${{ github.event.inputs.AWS_ACCOUNT_ID }}
      REGION: ${{ github.event.inputs.REGION }}

  linter:
    runs-on: ubuntu-latest
    needs: [ setup-environment ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup go environment
        uses: actions/setup-go@v5.0.2
        with:
          go-version: ${{ env.GO_VERSION }}

  build:
    runs-on: ubuntu-latest
    needs: [ setup-environment ]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup go env
      uses: actions/setup-go@v5.0.2
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Install dependencies
      run: go mod tidy

    - name: Build image
      env:
        REPO_NAME: ${{ needs.setup-environment.outputs.REPO_NAME }}
        MAIN_GO_FILE: ${{ needs.setup-environment.outputs.MAIN_GO_FILE }}
      run: go build -v -o $REPO_NAME $MAIN_GO_FILE

  package-and-publish:
    runs-on: ubuntu-latest
    needs: [ setup-environment, build, linter ]
    permissions:
      id-token: write
      contents: read
    outputs:
        REGISTRY: ${{ steps.set-registry-output.outputs.REGISTRY }}
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ needs.setup-environment.outputs.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set REGISTRY output
        id: set-registry-output
        run: echo "REGISTRY=${{ steps.login-ecr.outputs.registry }}" >> "$GITHUB_OUTPUT"

      - name: Build, tag, and push Docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ needs.setup-environment.outputs.REPO_NAME }}
          REGION: ${{ needs.setup-environment.outputs.AWS_REGION }}
          IMAGE_TAG: ${{ needs.setup-environment.outputs.IMAGE_TAG }}
        run: | # Check if repository already exists.
          aws ecr describe-repositories --repository-names ${REPOSITORY} || aws ecr create-repository --repository-name ${REPOSITORY} --region ${REGION}
          docker build  --build-arg GITHUB_TOKEN=${{ secrets.GH_PIPELINE_TOKEN_ACTIONS }} -t $REGISTRY/$REPOSITORY:$IMAGE_TAG . 
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

  infra-as-code:
    runs-on: ubuntu-latest
    needs: [ setup-environment, linter, build ]
    permissions:
      id-token: write
      contents: read
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ needs.setup-environment.outputs.AWS_REGION }}

      - name: Execute Cloudformation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        env:
          REPO_NAME: ${{ needs.setup-environment.outputs.REPO_NAME }}
          ENVIRONMENT: ${{ needs.setup-environment.outputs.ENVIRONMENT }}
          TEMPLATE_PATH: ${{ needs.setup-environment.outputs.CLOUDFORMATION_TEMPLATE_PATH }}
          TEMPLATE_PARAMETERS_PATH: ${{ needs.setup-environment.outputs.CLOUDFORMATION_TEMPLATE_PARAMETERS_PATH }}
        with:
          name: ${{ env.REPO_NAME }}-stack
          template: ${{ env.TEMPLATE_PATH }}
          parameter-overrides: ${{ env.TEMPLATE_PARAMETERS_PATH }}
          no-fail-on-empty-changeset: "1"
          capabilities: CAPABILITY_AUTO_EXPAND,CAPABILITY_NAMED_IAM